/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main;

import java.awt.Color;

/**
 *
 * @author Dre
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        Sidebar = new javax.swing.JPanel();
        LogoPilihT = new javax.swing.JLabel();
        PilihT = new javax.swing.JLabel();
        LogoPerawtanT = new javax.swing.JLabel();
        PerawatanT = new javax.swing.JLabel();
        LogoLangkahT = new javax.swing.JLabel();
        LangkahT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo128.png"))); // NOI18N
        TopPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 120));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/TopPanel.png"))); // NOI18N
        TopPanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 160));

        getContentPane().add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Sidebar.setBackground(new java.awt.Color(170, 222, 135));
        Sidebar.setLayout(new java.awt.GridLayout(3, 2, 5, 10));

        LogoPilihT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoPilihT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PilihTanaman.png"))); // NOI18N
        Sidebar.add(LogoPilihT);

        PilihT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/TxtPilihT.png"))); // NOI18N
        Sidebar.add(PilihT);

        LogoPerawtanT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoPerawtanT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PerawatanTanaman.png"))); // NOI18N
        Sidebar.add(LogoPerawtanT);

        PerawatanT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/TxtPerawatanT.png"))); // NOI18N
        Sidebar.add(PerawatanT);

        LogoLangkahT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLangkahT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LangkahTanam.png"))); // NOI18N
        Sidebar.add(LogoLangkahT);

        LangkahT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/TxtLangkahT.png"))); // NOI18N
        Sidebar.add(LangkahT);

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LangkahT;
    private javax.swing.JLabel LogoLangkahT;
    private javax.swing.JLabel LogoPerawtanT;
    private javax.swing.JLabel LogoPilihT;
    private javax.swing.JLabel PerawatanT;
    private javax.swing.JLabel PilihT;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
